### ISSUE TITLE
Sprint 3 - Crear servicios para la empresa

### ISSUE THREAD

**Issue by cdlavacudeg** [Budget-Guardian/budget-guardian#11]
- [x] El sistema permite consultar todas las empresas
- [x] El sistema permite consultar una sola empresa
- [x] El sistema permite crear una empresa
- [x] El sistema permite editar una empresa
- [x] El sistema permite eliminar una empresa

**Comment by WilliamBojaca** [comment]
Tareas Realizadas:

- Consulta de todas las empresas.
- Consulta de una empresa.
- Creación de una empresa.
- Edición de una empresa.
- Eliminación de una empresa.
