### ISSUE TITLE
Sprint 2 - Modelar una empresa como una clase de Java

### ISSUE THREAD

**Issue by cdlavacudeg** [Budget-Guardian/budget-guardian#2]
- [x] Es posible crear una instancia de la clase "Empresa"
- [x] Es posible leer y modificar el nombre de la empresa
- [x] Es posible leer y modificar la dirección de la empresa
- [x] Es posible leer y modificar el teléfono de la empresa
- [x] Es posible leer y modificar el NIT de la empresa

**Comment by WilliamBojaca** [comment]
**Tareas Realizadas:**

>  Es posible crear una instancia de la clase "Empresa".

>  Es posible leer y modificar el nombre de la empresa.

>  Es posible leer y modificar la dirección de la empresa.

>  Es posible leer y modificar el teléfono de la empresa.

>  Es posible leer y modificar el NIT de la empresa.
